# Generated by Django 4.2 on 2023-09-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("email", "phone_number"), name="unique_email_and_phone_number"
            ),
        ),
    ]
