# Generated by Django 4.2 on 2023-09-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_contact_unique_email_and_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(default=1, max_length=50, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(default=1, max_length=50, verbose_name="Фамилия"),
            preserve_default=False,
        ),
    ]
